services:
  db:
    image: postgres:16
    container_name: pockets-db
    restart: always
    environment:
      POSTGRES_USER: pockets_user
      POSTGRES_PASSWORD: pockets_pass
      POSTGRES_DB: pockets_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
